version: "3.7"

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-net
    restart: unless-stopped

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - monitoring-net
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/mnt/config/promtail/promtail-config.yaml
    depends_on:
      - loki
    command: -config.file=/mnt/config/promtail/promtail-config.yaml
    networks:
      - monitoring-net
    restart: unless-stopped

volumes:
  grafana-storage:

networks:
  monitoring-net:
    driver: bridge
